create_ticket:
  path: /v1/ticket
  controller: TicketSystem\Ticket\Infrastructure\Communication\Http\Symfony\Controller\TicketController::create
  methods: POST

next_ticket:
  path: /v1/ticket/next
  controller: TicketSystem\Ticket\Infrastructure\Communication\Http\Symfony\Controller\TicketController::next
  methods: GET
